service: NorthwindTraders

frameworkVersion: "3"

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  profile: myawff
  region: us-east-1
  environment:
    NORTHWIND_TRADERS_DB_USERNAME: ${ssm:NORTHWIND_TRADERS_USERNAME}
    NORTHWIND_TRADERS_DB_PASSWORD: ${ssm:NORTHWIND_TRADERS_PASSWORD}
    NORTHWIND_TRADERS_DB_ENDPOINT: ${ssm:NORTHWIND_TRADERS_DB_ENDPOINT}
    NORTHWIND_TRADERS_DB_PORT: ${ssm:NORTHWIND_TRADERS_DB_PORT}
    NORTHWIND_TRADERS_DB_NAME: ${ssm:NORTHWIND_TRADERS_DB_NAME}

functions:
  getAllSuppliers:
    handler: src/lambdas/suppliers/getAllSuppliers.handler
    events:
      - http:
          path: suppliers
          method: get
          cors: true
  getAllProducts:
    handler: src/lambdas/products/getAllProducts.handler
    events:
      - http:
          path: products
          method: get
          cors: true
  getAllEmployees:
    handler: src/lambdas/employees/getAllEmployees.handler
    events:
      - http:
          path: employees
          method: get
          cors: true
  getAllCustomers:
    handler: src/lambdas/customers/getAllCustomers.handler
    events:
      - http:
          path: customers
          method: get
          cors: true
  getAllOrders:
    handler: src/lambdas/orders/getAllOrders.handler
    events:
      - http:
          path: orders
          method: get
          cors: true
  getSupplierById:
    handler: src/lambdas/suppliers/getSupplierById.handler
    events:
      - http:
          path: supplier
          method: get
          cors: true
  getCustomerById:
    handler: src/lambdas/customers/getCustomerById.handler
    events:
      - http:
          path: customer
          method: get
          cors: true
  getProductById:
    handler: src/lambdas/products/getProductById.handler
    events:
      - http:
          path: product
          method: get
          cors: true
  searchObjects:
    handler: src/lambdas/searchObjects.handler
    events:
      - http:
          path: search
          method: get
          cors: true 

resources:
  Resources:
    NorthwindTradersDB:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: MySQL
        DBName: NorthwindTradersDB
        DBInstanceClass: db.t3.micro
        MasterUsername: ${ssm:NORTHWIND_TRADERS_USERNAME}
        MasterUserPassword: ${ssm:NORTHWIND_TRADERS_PASSWORD}
        AllocatedStorage: 5
        BackupRetentionPeriod: 0
        PubliclyAccessible: true
