export type EnvVariables =
  | "NORTHWIND_TRADERS_DB_USERNAME"
  | "NORTHWIND_TRADERS_DB_PASSWORD"
  | "NORTHWIND_TRADERS_DB_ENDPOINT"
  | "NORTHWIND_TRADERS_DB_PORT"
  | "NORTHWIND_TRADERS_DB_NAME"
  | "API_ENDPOINT";
